---
deployment:
  tasks:
    - export DEPLOYPATH=/home/aapjgfju/public_html/soki-app.digipassplatinum.my.id
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -rf dist/* $DEPLOYPATH/
    - /bin/cp -f dist/.htaccess $DEPLOYPATH/.htaccess
    - /bin/cp -f dist/api.php $DEPLOYPATH/api.php
